(()=>{'use strict';
const $=s=>document.querySelector(s),opp=[['BamBam22',1449,'BB','alt2'],['QueenTile',1503,'QT','alt3'],['MahjMama',1521,'MM','alt4']],pass=[['First Charleston · Pass Right',1],['First Charleston · Pass Across',2],['First Charleston · Pass Left',3]],A={0:[50,87],1:[85,50],2:[50,13],3:[15,50],d:[50,50]},WG={E:'東',S:'南',W:'西',N:'北'},DG={R:'龍',G:'發',0:'白'};
let S={deck:[],h:[[],[],[],[]],x:[[],[],[],[]],d:[],sel:new Set,phase:'lobby',cs:0,turn:0,drawn:false,claim:false,feed:[],timers:[],sound:true,last:null};
const later=(f,t)=>{let i=setTimeout(f,t);S.timers.push(i);return i},clear=()=>{S.timers.forEach(clearTimeout);S.timers=[]},sh=a=>{for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function set(){let a=[],id=0;for(let s of ['bam','crak','dot'])for(let r=1;r<=9;r++)for(let c=0;c<4;c++)a.push({id:id++,s,r,l:`${r} ${s==='bam'?'Bam':s==='crak'?'Crak':'Dot'}`});for(let r of ['E','S','W','N'])for(let c=0;c<4;c++)a.push({id:id++,s:'wind',r,l:`${r} Wind`});for(let r of ['R','G','0'])for(let c=0;c<4;c++)a.push({id:id++,s:'dragon',r,l:r==='R'?'Red Dragon':r==='G'?'Green Dragon':'White Dragon'});for(let r=1;r<=8;r++)a.push({id:id++,s:'flower',r,l:`Flower ${r}`});for(let r=1;r<=8;r++)a.push({id:id++,s:'joker',r,l:'Joker'});return a}
const order=t=>({bam:1,crak:2,dot:3,wind:4,dragon:5,flower:6,joker:7})[t.s]||9,sort=h=>h.sort((a,b)=>order(a)-order(b)||(typeof a.r==='number'&&typeof b.r==='number'?a.r-b.r:String(a.r).localeCompare(String(b.r))));
function face(t){if(t.s==='bam')return `<b>${t.r}</b><em>竹</em>`;if(t.s==='crak')return `<b>${t.r}</b><em>萬</em>`;if(t.s==='dot')return `<b>${t.r}</b><em>●</em>`;if(t.s==='wind')return `<em>${WG[t.r]}</em><small>${t.r}</small>`;if(t.s==='dragon')return `<em>${DG[t.r]}</em><small>${t.r==='R'?'Red':t.r==='G'?'Green':'White'}</small>`;if(t.s==='flower')return `<em>✿</em><small>Flower</small>`;return `<em>JOKER</em><small>Wild</small>`}
function tile(t,hide=false){let e=document.createElement('div');e.className=`tile ${hide?'concealed':t.s}`;if(!hide){e.innerHTML=`<div class="tile-inner">${face(t)}</div>`;e.title=t.l}return e}
function feed(w,m){S.feed.unshift([w,m]);S.feed=S.feed.slice(0,14)}
function render(){let r=$('#playerRack');r.innerHTML='';S.h[0].forEach(t=>{let e=tile(t);if(S.sel.has(t.id))e.classList.add('selected');e.onclick=()=>pick(t.id);r.append(e)});for(let p=1;p<4;p++){let q=$(`#rack${p}`);q.innerHTML='';S.h[p].forEach(()=>q.append(tile({},true)))}for(let p=0;p<4;p++){let q=$(`#exposed${p}`);if(q){q.innerHTML='';S.x[p].forEach(t=>q.append(tile(t)))}}let f=$('#discardField');f.innerHTML='';S.d.forEach(o=>f.append(tile(o.t)));$('#tableFeed').innerHTML=S.feed.map(x=>`<div class="feed-item"><strong>${x[0]}</strong> ${x[1]}</div>`).join('');let c=an(S.h[0]);$('#pairCount').textContent=c.p;$('#bestSuit').textContent=c.b;$('#flexScore').textContent=c.f+'%';$('#wallCount').textContent=S.deck.length;$('#wallMeter').style.width=Math.min(100,S.deck.length)+'%';phase(c)}
function an(h){let m={},s={bam:0,crak:0,dot:0};h.forEach(t=>{let k=t.s+':'+t.r;m[k]=(m[k]||0)+1;if(s[t.s]!=null)s[t.s]++});let p=Object.values(m).filter(v=>v>1).length,b=Object.entries(s).sort((a,b)=>b[1]-a[1])[0];return{p,b:{bam:'Bams',crak:'Craks',dot:'Dots'}[b[0]],f:Math.min(99,45+p*8+b[1]*3)}}
function hint(h){let m={};h.forEach(t=>m[t.s+':'+t.r]=(m[t.s+':'+t.r]||0)+1);return h.filter(t=>t.s!=='joker').map(t=>[t,(m[t.s+':'+t.r]-1)*25+(['bam','crak','dot'].includes(t.s)?h.filter(x=>x.s===t.s&&Math.abs(x.r-t.r)<=2).length*4:0)+(t.s==='flower'?4:0)]).sort((a,b)=>a[1]-b[1])[0]?.[0]||h[0]}
function phase(c){let b=$('#primaryActionBtn'),txt;if(S.phase==='charleston'){txt=pass[S.cs][0];b.textContent='Pass 3 Tiles';b.disabled=S.sel.size!==3;$('#turnOrb').textContent='C';$('#coachText').textContent=S.sel.size?`${S.sel.size}/3 selected.`:`Select three tiles to pass. Preserve pairs and Jokers; strongest suit: ${c.b}.`}else if(S.phase==='play'){if(S.claim){txt='Discard window · waiting for calls';b.textContent='Waiting…';b.disabled=true;$('#coachText').textContent='A discard claim window is open before the next draw.'}else if(S.turn===0){txt=S.drawn?'Your turn · Choose a discard':'Your turn · Draw';b.textContent=S.drawn?'Discard Tile':'Draw Tile';b.disabled=S.drawn?S.sel.size!==1:false;$('#turnOrb').textContent='BG';$('#coachText').textContent=S.drawn?`Consider ${hint(S.h[0]).l}.`:'Draw from the wall.'}else{let o=opp[S.turn-1];txt=o[0]+"'s turn";b.textContent='Waiting…';b.disabled=true;$('#turnOrb').textContent=o[2];$('#coachText').textContent='Watch the table while the other player acts.'}}else{txt='Hand complete';b.textContent='Return to Lobby';b.disabled=false}$('#phaseLabel').textContent=txt}
function pick(id){if(S.claim)return;if(S.phase==='charleston'){S.sel.has(id)?S.sel.delete(id):S.sel.size<3&&S.sel.add(id)}else if(S.phase==='play'&&S.turn===0&&S.drawn){S.sel.clear();S.sel.add(id)}render();tone(420,.012)}
function fly(ts,a,b){let L=$('#tableAnimLayer'),T=$('#mahjongTable').getBoundingClientRect(),p=A[a],q=A[b];ts.forEach((t,i)=>{let w=document.createElement('div');w.className='flying-tile';w.style.left=T.width*p[0]/100-21+'px';w.style.top=T.height*p[1]/100-29+'px';w.append(tile(t));L.append(w);later(()=>{w.style.transform=`translate(${T.width*(q[0]-p[0])/100}px,${T.height*(q[1]-p[1])/100}px) rotate(${q[0]>p[0]?12:-12}deg)`;w.style.opacity='.08'},i*70);later(()=>w.remove(),900+i*70)})}
function botpass(h){return sh(h.filter(t=>t.s!=='joker').slice()).slice(0,3)}
function dopass(){if(S.sel.size!==3)return;let [lab,o]=pass[S.cs],out=S.h.map((h,p)=>p?botpass(h):h.filter(t=>S.sel.has(t.id))),inc=[[],[],[],[]];for(let p=0;p<4;p++)inc[(p+o)%4]=out[p];for(let p=0;p<4;p++){let ids=new Set(out[p].map(t=>t.id));S.h[p]=S.h[p].filter(t=>!ids.has(t.id)).concat(inc[p]);sort(S.h[p]);fly(out[p],p,(p+o)%4)}feed('Charleston',lab.replace('First Charleston · ','')+' complete.');S.sel.clear();S.cs++;render();tone(560,.02);if(S.cs===3)later(()=>{S.phase='play';S.turn=0;feed('Table','Charleston complete. Your turn begins.');render()},850)}
function draw(p){if(!S.deck.length){S.phase='ended';feed('Table','The wall is exhausted.');render();return null}let t=S.deck.pop();S.h[p].push(t);return t}
function banner(title,text,d=1800){let b=$('#claimBanner'),m=$('#claimMeter');$('#claimTitle').textContent=title;$('#claimText').textContent=text;b.classList.add('show');m.style.transition='none';m.style.width='100%';requestAnimationFrame(()=>{m.style.transition=`width ${d}ms linear`;m.style.width='0%'})}
function unbanner(){$('#claimBanner').classList.remove('show')}
function canclaim(p,t){return S.h[p].filter(x=>x.s===t.s&&x.r===t.r).length>=2&&Math.random()<.5}
function openclaim(dis,t,next){S.claim=true;S.last={p:dis,t};banner('Discard window',`Players may claim ${t.l} before the next draw.`);render();later(()=>resolve(next),1820)}
function resolve(next){let {p,t}=S.last;for(let k=1;k<4;k++){let q=(p+k)%4;if(q&&canclaim(q,t)){let a=[];for(let i=S.h[q].length-1;i>=0&&a.length<2;i--)if(S.h[q][i].s===t.s&&S.h[q][i].r===t.r)a.push(...S.h[q].splice(i,1));S.x[q].push(...a,t);S.d.pop();feed(opp[q-1][0],`claimed ${t.l}.`);fly([t],'d',q);banner('Tile claimed',`${opp[q-1][0]} takes ${t.l}.`,1100);render();return later(()=>{unbanner();S.claim=false;S.turn=q;render();botdiscard(q)},1150)}}later(()=>{unbanner();S.claim=false;S.turn=next;if(next===0)S.drawn=false;render();if(next)botturn()},1800)}
function pdraw(){let t=draw(0);if(t){S.drawn=true;sort(S.h[0]);feed('Brandon','drew a tile.');render();tone(620,.02)}}
function pdiscard(){let id=[...S.sel][0],i=S.h[0].findIndex(t=>t.id===id);if(i<0)return;let t=S.h[0].splice(i,1)[0];S.d.push({p:0,t});S.sel.clear();S.drawn=false;feed('Brandon',`discarded ${t.l}.`);render();tone(220,.02);openclaim(0,t,1)}
function botchoice(h){return h.map(t=>[t,(t.s==='joker'?100:t.s==='flower'?10:0)+h.filter(x=>x.s===t.s&&x.r===t.r).length*20]).sort((a,b)=>a[1]-b[1])[0][0]}
function botdiscard(p){let t=botchoice(S.h[p]),i=S.h[p].findIndex(x=>x.id===t.id);S.h[p].splice(i,1);S.d.push({p,t});feed(opp[p-1][0],`discarded ${t.l}.`);render();openclaim(p,t,(p+1)%4)}
function botturn(){if(S.claim||!S.turn)return;later(()=>{let p=S.turn,t=draw(p);if(!t)return;sort(S.h[p]);feed(opp[p-1][0],'drew a tile.');render();later(()=>botdiscard(p),650)},850)}
function action(){if(S.phase==='charleston')dopass();else if(S.phase==='play'&&S.turn===0&&!S.claim)S.drawn?pdiscard():pdraw();else if(S.phase==='ended')lobby()}
function suggest(){if(S.phase==='charleston'){S.sel.clear();let h=S.h[0].filter(t=>t.s!=='joker').slice();for(let i=0;i<3;i++){let t=hint(h);S.sel.add(t.id);h.splice(h.findIndex(x=>x.id===t.id),1)}toast('Suggested Charleston pass selected.')}else if(S.phase==='play'&&S.turn===0&&S.drawn){S.sel.clear();let t=hint(S.h[0]);S.sel.add(t.id);toast(`Suggestion: discard ${t.l}.`)}render()}
function start(){clear();S.deck=sh(set());S.h=[[],[],[],[]];S.x=[[],[],[],[]];for(let r=0;r<13;r++)for(let p=0;p<4;p++)S.h[p].push(S.deck.pop());S.h.forEach(sort);Object.assign(S,{d:[],sel:new Set,phase:'charleston',cs:0,turn:0,drawn:false,claim:false,feed:[],last:null});feed('Table','Tiles dealt. First Charleston begins.');$('#matchModal').classList.remove('open');$('#lobbyView').classList.remove('active');$('#gameView').classList.add('active');unbanner();render();tone(700,.025)}
function match(pr=false){let M=$('#matchModal'),L=$('#matchList');M.classList.add('open');$('#matchTitle').textContent=pr?'Preparing practice table…':'Finding your table…';$('#matchSubtitle').textContent=pr?'Three club bots are taking their seats.':'Searching for players within ±100 rating.';L.innerHTML='';clear();opp.forEach((o,i)=>later(()=>{L.insertAdjacentHTML('beforeend',`<div class="match-player"><div class="match-player-left"><div class="avatar ${o[3]}">${o[2]}</div><strong>${o[0]}</strong></div><span>${pr?'Club bot':o[1]}</span></div>`);if(i===2){$('#matchTitle').textContent='Table found';later(start,650)}},350+i*520))}
function lobby(){clear();S.phase='lobby';S.claim=false;unbanner();$('#gameView').classList.remove('active');$('#lobbyView').classList.add('active');$('#matchModal').classList.remove('open');$('#tableAnimLayer').innerHTML=''}
function toast(m){let e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1700)}
function tone(f=440,v=.015){if(!S.sound)return;try{let C=window.AudioContext||window.webkitAudioContext,c=new C,o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.setValueAtTime(v,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.07);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.08)}catch(e){}}
function init(){$('#quickMatchBtn').onclick=$('#quickModeCard').onclick=()=>match(false);$('#practiceBtn').onclick=()=>match(true);$('#friendModeCard').onclick=()=>toast('Private tables are next.');$('#cancelMatchBtn').onclick=$('#leaveGameBtn').onclick=$('#brandHome').onclick=lobby;$('#primaryActionBtn').onclick=action;$('#sortBtn').onclick=()=>{sort(S.h[0]);render()};$('#suggestBtn').onclick=suggest;$('#soundToggle').onclick=()=>{S.sound=!S.sound;toast(S.sound?'Sound on':'Sound off')};render()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();})();